In [1]:
import pandas as pd
import numpy as np

In [7]:
sales = pd.read_csv('sales_returns.csv')
sales

order_id order_date ship_date       ship_mode customer_id  \
0     CA-2015-143336   27/08/15  01/09/15    Second Class    ZD-21925   
1     CA-2015-143336   27/08/15  01/09/15    Second Class    ZD-21925   
2     CA-2015-143336   27/08/15  01/09/15    Second Class    ZD-21925   
3     CA-2017-111682   17/06/17  18/06/17     First Class    TB-21055   
4     CA-2017-111682   17/06/17  18/06/17     First Class    TB-21055   
...              ...        ...       ...             ...         ...   
1297  US-2015-143287   11/11/15  17/11/15  Standard Class    KN-16705   
1298  US-2015-143287   11/11/15  17/11/15  Standard Class    KN-16705   
1299  CA-2018-121258   26/02/18  03/03/18  Standard Class    DB-13060   
1300  CA-2018-121258   26/02/18  03/03/18  Standard Class    DB-13060   
1301  CA-2018-121258   26/02/18  03/03/18  Standard Class    DB-13060   

           customer_name  cust_age cust_gender      segment        country  \
0     Zuschuss Donatelli        19      Female     Consumer  United States   
1     Zuschuss Donatelli        19      Female     Consumer  United States   
2     Zuschuss Donatelli        19      Female     Consumer  United States   
3        Ted Butterfield        20      Female     Consumer  United States   
4        Ted Butterfield        20      Female     Consumer  United States   
...                  ...       ...         ...          ...            ...   
1297       Kristina Nunn        19      Female  Home Office  United States   
1298       Kristina Nunn        24        Male  Home Office  United States   
1299         Dave Brooks        21      Female     Consumer  United States   
1300         Dave Brooks        23      Female     Consumer  United States   
1301         Dave Brooks        21      Female     Consumer  United States   

      ... region       product_id         category sub_category  \
0     ...   West  OFF-AR-10003056  Office Supplies          Art   
1     ...   West  TEC-PH-10001949       Technology       Phones   
2     ...   West  OFF-BI-10002215  Office Supplies      Binders   
3     ...   East  OFF-ST-10000604  Office Supplies      Storage   
4     ...   East  OFF-PA-10001569  Office Supplies        Paper   
...   ...    ...              ...              ...          ...   
1297  ...   East  OFF-PA-10004039  Office Supplies        Paper   
1298  ...   East  OFF-SU-10001574  Office Supplies     Supplies   
1299  ...   West  FUR-FU-10000747        Furniture  Furnishings   
1300  ...   West  TEC-PH-10003645       Technology       Phones   
1301  ...   West  OFF-PA-10004041  Office Supplies        Paper   

                                           product_name    sales quantity  \
0                                            Newell 341    8.560        2   
1                               Cisco SPA 501G IP Phone  213.480        3   
2           Wilson Jones Hanging View Binder, White, 1"   22.720        4   
3                       Home/Office Personal File Carts  208.560        6   
4                                             Xerox 232   32.400        5   
...                                                 ...      ...      ...   
1297                                         Xerox 1882  223.920        4   
1298                           Acme Value Line Scissors    7.300        2   
1299  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960        2   
1300                              Aastra 57i VoIP phone  258.576        2   
1301  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600        4   

     discount    profit  returned  
0         0.0    2.4824      True  
1         0.2   16.0110      True  
2         0.2    7.3840      True  
3         0.0   52.1400      True  
4         0.0   15.5520      True  
...       ...       ...       ...  
1297      0.0  109.7208      True  
1298      0.0    2.1900      True  
1299      0.0   15.6332      True  
1300      0.2   19.3932      True  
1301      0.0   13.3200      True  

[1302 rows x 23 columns]

In [8]:
# To display first five records
sales.head()

order_id order_date ship_date     ship_mode customer_id  \
0  CA-2015-143336   27/08/15  01/09/15  Second Class    ZD-21925   
1  CA-2015-143336   27/08/15  01/09/15  Second Class    ZD-21925   
2  CA-2015-143336   27/08/15  01/09/15  Second Class    ZD-21925   
3  CA-2017-111682   17/06/17  18/06/17   First Class    TB-21055   
4  CA-2017-111682   17/06/17  18/06/17   First Class    TB-21055   

        customer_name  cust_age cust_gender   segment        country  ...  \
0  Zuschuss Donatelli        19      Female  Consumer  United States  ...   
1  Zuschuss Donatelli        19      Female  Consumer  United States  ...   
2  Zuschuss Donatelli        19      Female  Consumer  United States  ...   
3     Ted Butterfield        20      Female  Consumer  United States  ...   
4     Ted Butterfield        20      Female  Consumer  United States  ...   

  region       product_id         category sub_category  \
0   West  OFF-AR-10003056  Office Supplies          Art   
1   West  TEC-PH-10001949       Technology       Phones   
2   West  OFF-BI-10002215  Office Supplies      Binders   
3   East  OFF-ST-10000604  Office Supplies      Storage   
4   East  OFF-PA-10001569  Office Supplies        Paper   

                                  product_name   sales quantity discount  \
0                                   Newell 341    8.56        2      0.0   
1                      Cisco SPA 501G IP Phone  213.48        3      0.2   
2  Wilson Jones Hanging View Binder, White, 1"   22.72        4      0.2   
3              Home/Office Personal File Carts  208.56        6      0.0   
4                                    Xerox 232   32.40        5      0.0   

    profit  returned  
0   2.4824      True  
1  16.0110      True  
2   7.3840      True  
3  52.1400      True  
4  15.5520      True  

[5 rows x 23 columns]

In [9]:
# To see structure of data , total number of rows and column present 
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   order_id       1302 non-null   object 
 1   order_date     1302 non-null   object 
 2   ship_date      1302 non-null   object 
 3   ship_mode      1302 non-null   object 
 4   customer_id    1302 non-null   object 
 5   customer_name  1302 non-null   object 
 6   cust_age       1302 non-null   int64  
 7   cust_gender    1302 non-null   object 
 8   segment        1302 non-null   object 
 9   country        1302 non-null   object 
 10  city           1302 non-null   object 
 11  state          1302 non-null   object 
 12  postal_code    1302 non-null   int64  
 13  region         1302 non-null   object 
 14  product_id     1302 non-null   object 
 15  category       1302 non-null   object 
 16  sub_category   1302 non-null   object 
 17  product_name   1302 non-null   object 
 18  sales   

In [10]:
# Filtering and taking only 4 fields for further analysis
X = sales.loc[:,['cust_age','cust_gender','city','sub_category']]
y = sales.returned
X.head()

cust_age cust_gender           city sub_category
0        19      Female  San Francisco          Art
1        19      Female  San Francisco       Phones
2        19      Female  San Francisco      Binders
3        20      Female           Troy      Storage
4        20      Female           Troy        Paper

In [13]:
# Converting text data to number because machine learning understand number better
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
X.cust_gender = enc.fit_transform(X.cust_gender)
X.city = enc.fit_transform(X.city)
X.sub_category = enc.fit_transform(X.sub_category)
X.head()

cust_age  cust_gender  city  sub_category
0        19            0   156             2
1        19            0   156            13
2        19            0   156             3
3        20            0   173            14
4        20            0   173            12

In [14]:
# Using mL model 
from sklearn.ensemble import RandomForestClassifier
mod = RandomForestClassifier()
mod.fit(X,y)

RandomForestClassifier()

In [15]:
mod

RandomForestClassifier()

In [16]:
y

0       True
1       True
2       True
3       True
4       True
        ... 
1297    True
1298    True
1299    True
1300    True
1301    True
Name: returned, Length: 1302, dtype: bool

In [17]:
# Checking by taking random customer data
mod.predict([[27,1,100,10]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([False])

* So False means this order will not returned.

In [18]:
mod.predict([[25,0,90,15]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([False])

In [19]:
mod.predict([[22,1,100,8]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([ True])

* Might be this order will return

In [20]:
# Checking accuracy of model
mod.score(X,y)

0.999231950844854

* Getting 99% of accuracy 


### We can this model as an API and connect with amaon order system. So when order come it will predict high probability of return or not