In [1]:
import pandas as pd
import numpy as np


In [2]:
ins = pd.read_csv('insurance_data.csv')
ins.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [3]:
ins.shape

(27, 2)

In [4]:
ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 560.0 bytes


In [7]:
ins.bought_insurance.unique()

array([0, 1], dtype=int64)

In [8]:
ins.isnull().sum()

age                 0
bought_insurance    0
dtype: int64

In [9]:
X = ins[['age']]
y = ins[['bought_insurance']]

In [11]:
ins.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
dtype: bool

In [13]:
ins.drop_duplicates(inplace=True)

In [14]:
ins.shape

(26, 2)

In [15]:
X = ins[['age']]
y = ins[['bought_insurance']]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
model = LogisticRegression()
model

LogisticRegression()

In [20]:
model.fit(X_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [21]:
y_train.shape

(20, 1)

In [26]:
X_train.shape

(20, 1)

In [27]:
X_test.shape

(6, 1)

In [28]:
y_predict = model.predict(X_test)
y_predict

array([0, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
X_test

age
26   23
4    46
23   45
6    55
5    56
7    60

In [31]:
y_test

bought_insurance
26                 0
4                  1
23                 1
6                  0
5                  1
7                  1

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [33]:
accuracy_score(y_test,y_predict)

0.8333333333333334

In [34]:
confusion_matrix(y_test,y_predict)

array([[1, 1],
       [0, 4]], dtype=int64)

In [35]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.80      1.00      0.89         4

    accuracy                           0.83         6
   macro avg       0.90      0.75      0.78         6
weighted avg       0.87      0.83      0.81         6

