### Agenda
* Numpy introduction
* Array Creation --> 1D,2D,3D
* Attributes   -->ndim,size,shape,dtype
* Functions   -->arange,linespace,ravel,random,rand
* Stacking   -->hstack,vstack
* Splitting  -->hsplit,vsplit
* Matrix operation
* BroadCasting,masking
* Other Function  -> eye,zeros,ones,max,min,copy,transpose


### Numpy stands for Numerical Python
* Homogeneous multi-dimensional collection of element
* Scientific and mathematical computations
* Array is a collection of element with same data type


### Why use NumPy?
* Numpy arrays are faster and more compact than python lists
* Numpy uses much less memory to store data

In [1]:
# import package
import numpy as np

In [2]:
np.random.random(100).reshape(1,2,5,5,2,1,1,1,1,1)

array([[[[[[[[[[ 0.56689771]]]]],




           [[[[[ 0.54378473]]]]]],





          [[[[[[ 0.47518606]]]]],




           [[[[[ 0.72227108]]]]]],





          [[[[[[ 0.50373952]]]]],




           [[[[[ 0.52183511]]]]]],





          [[[[[[ 0.50765418]]]]],




           [[[[[ 0.09811264]]]]]],





          [[[[[[ 0.43109854]]]]],




           [[[[[ 0.50917096]]]]]]],






         [[[[[[[ 0.46117059]]]]],




           [[[[[ 0.18148034]]]]]],





          [[[[[[ 0.68118931]]]]],




           [[[[[ 0.98187535]]]]]],





          [[[[[[ 0.15433813]]]]],




           [[[[[ 0.40433166]]]]]],





          [[[[[[ 0.56007487]]]]],




           [[[[[ 0.77213771]]]]]],





          [[[[[[ 0.30953784]]]]],




           [[[[[ 0.08193996]]]]]]],






         [[[[[[[ 0.53721099]]]]],




           [[[[[ 0.94424897]]]]]],





          [[[[[[ 0.50017457]]]]],




           [[[[[ 0.4065295 ]]]]]],





          [[[[[[ 0.83856387]]]]],




           [[[[[ 0.027

In [3]:
# 1-D array
a1 = np.array([5,6,9,15])
a1

array([ 5,  6,  9, 15])

In [4]:
type(a1)

numpy.ndarray

In [5]:
# Atrributes
print(a1.ndim)   # dimension of array
print(a1.size)   # no of elements in array
print(a1.dtype)  # dtype of elements
print(a1.shape)  # no of elements in each dimensions

1
4
int32
(4,)


## 2-D array shape (4,3)
* 2 dimension is a collection of 1 dimension array





In [6]:
a2 = np.array([[4,5,6],[14,5,16],[24,65,16],[48,85,61]])
a2


array([[ 4,  5,  6],
       [14,  5, 16],
       [24, 65, 16],
       [48, 85, 61]])

In [7]:
print(a2.ndim)   # dimension of array
print(a2.size)   # no of elements in array
print(a2.dtype)  # dtype of elements
print(a2.shape)

2
12
int32
(4, 3)


In [8]:
a3 = np.array([[4,5,6],[14,5,16],[24,65],[48,85,61]])
a3

array([[4, 5, 6], [14, 5, 16], [24, 65], [48, 85, 61]], dtype=object)

In [9]:
type(a3)

numpy.ndarray

In [10]:
## Create 2D array of share(4,2)

a4 = np.array([[1,2],[3,4],[5,6],[7,8]])
a4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
## 3-D array(2,2,3)

a5 = np.array([[[2,4,6],[1,2,3]],[[6,8,9],[5,6,2]]])
a5

array([[[2, 4, 6],
        [1, 2, 3]],

       [[6, 8, 9],
        [5, 6, 2]]])

In [12]:
help('array')

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

In [13]:
2 ** 2 ** 3 ** 1  #(R->l)

256

In [14]:
2**8

256

In [15]:
2**5

32

#### Functions -> arange,reshape,linspace,ravel,random,rand

In [16]:
# arange -> 3 parameters -> start,stop(E),step
np.arange(5)   #stop(E)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,11) #start, stop(E)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11,2)   # start,stop(E),step

array([1, 3, 5, 7, 9])

In [19]:
## Q) Generate 50 to 41 by using arange function
np.arange(50,40,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41])

In [20]:
## Linspace --> equally space number within limit -> start,stop,count
np.linspace(1,10,5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [21]:
np.linspace(1,10,5,retstep=True)

(array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ]), 2.25)

In [22]:
np.linspace(10000,100000,10)

array([  10000.,   20000.,   30000.,   40000.,   50000.,   60000.,
         70000.,   80000.,   90000.,  100000.])

In [23]:
#retstep ---> give interval
np.linspace(10000,100000,10,dtype=int,retstep=True)

(array([ 10000,  20000,  30000,  40000,  50000,  60000,  70000,  80000,
         90000, 100000]), 10000.0)

In [24]:
np.linspace(10,100,7,retstep=True)

(array([  10.,   25.,   40.,   55.,   70.,   85.,  100.]), 15.0)

In [25]:
##ravel - convert nD array into 1D
np.ravel(a4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
np.linspace(2,20,10)

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

In [27]:
a4.shape

(4, 2)

In [28]:
a4.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
# Q) Create an array from 51 to 100 and the shape is (5,2,5)
np.arange(51,101)

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
np.arange(51,101).reshape(5,2,5)

array([[[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70]],

       [[ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90]],

       [[ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [31]:
# random --> use to create rando no b/w 0 to 1
np.random.random(5)

array([ 0.19452644,  0.65723702,  0.32071057,  0.57198783,  0.86601123])

In [32]:
np.random.random(10)

array([ 0.51538588,  0.51741382,  0.61229603,  0.2583583 ,  0.56584554,
        0.07128976,  0.77274262,  0.71098293,  0.0204881 ,  0.78569084])

In [33]:
np.random.random(10).reshape(5,2)

array([[ 0.2515622 ,  0.82917232],
       [ 0.56578259,  0.57249394],
       [ 0.83883744,  0.30067843],
       [ 0.87296268,  0.52143457],
       [ 0.41858111,  0.31171023]])

In [34]:
np.random.randint(5) #stop(E)

3

In [35]:
np.random.randint(1,15,3)  # start, Stop(E),count

array([8, 2, 4])

In [36]:
# USE IN OTP
np.random.randint(0,10000)


4259

In [37]:
# Q) Generate 10 random nos and convert into 6 digit int and reshape into 2,5
a = np.random.random(10).reshape(2,5)*1000000
np.round(a,0)

array([[  70989.,  436105.,  971153.,  715821.,  429159.],
       [ 849640.,  891229.,  466645.,  616985.,  330630.]])

In [38]:
np.floor(np.random.random(10)*1000000)

array([ 236126.,   74527.,  985825.,  399526.,  519401.,  221140.,
         79804.,  242240.,  270936.,  630179.])

In [39]:
## a.astype('int') --> convert data type into int any data type
a=np.random.random(10)*1000000
a.astype('int')

array([799860,  38157, 524069, 200606, 534116, 509166,   4142, 202983,
        96756, 351907])

In [40]:
## Stacking -->hstack,vstack
## In horizontal stacking rows should be equal
## In vertical Stacking columns should be equal
a2

array([[ 4,  5,  6],
       [14,  5, 16],
       [24, 65, 16],
       [48, 85, 61]])

In [41]:
d=np.arange(1,13).reshape(4,3)
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.hstack(a2)

array([ 4,  5,  6, 14,  5, 16, 24, 65, 16, 48, 85, 61])

In [43]:
np.hstack((a2,d))

array([[ 4,  5,  6,  1,  2,  3],
       [14,  5, 16,  4,  5,  6],
       [24, 65, 16,  7,  8,  9],
       [48, 85, 61, 10, 11, 12]])

In [44]:
np.vstack((a2,d))

array([[ 4,  5,  6],
       [14,  5, 16],
       [24, 65, 16],
       [48, 85, 61],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
new = np.arange(1,21).reshape(5,4)
new

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
## Splitting  --> hsplit , vsplit

np.hsplit((a2,2))

TypeError: hsplit() missing 1 required positional argument: 'indices_or_sections'

In [ ]:
np.vsplit((d,2))

### Matrix Operation

In [47]:
m1 = np.arange(12).reshape(4,3)
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
m2 = np.arange(11,23).reshape(4,3)
m2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [50]:
## Adition


np.add(m1,m2)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27],
       [29, 31, 33]])

In [51]:
np.subtract(m1,m2)

array([[-11, -11, -11],
       [-11, -11, -11],
       [-11, -11, -11],
       [-11, -11, -11]])

In [52]:
np.subtract(m2,m1)

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [53]:
np.divide(m1,m2)

array([[ 0.        ,  0.08333333,  0.15384615],
       [ 0.21428571,  0.26666667,  0.3125    ],
       [ 0.35294118,  0.38888889,  0.42105263],
       [ 0.45      ,  0.47619048,  0.5       ]])

In [58]:
m3=m1.reshape(3,4)
m3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
## multiplication   c1=r1

np.multiply(m1,m2)

array([[  0,  12,  26],
       [ 42,  60,  80],
       [102, 126, 152],
       [180, 210, 242]])

### Q) Create a random array of shape(4,3) and 
1) extract 2nd and 3 rd row
2) extract 2 nd column
3) extract last element

In [84]:
y=np.random.randint(1,100,12).reshape(4,3)
y

array([[67, 80, 23],
       [71, 26, 93],
       [34, 28,  9],
       [48, 17, 98]])

In [85]:
y[1:3]

array([[71, 26, 93],
       [34, 28,  9]])

In [86]:
y[:,1:2]   ## extract 2 nd column

array([[80],
       [26],
       [28],
       [17]])

In [90]:
type(y)    ## for all variables

numpy.ndarray

In [89]:
y.dtype

dtype('int32')

In [87]:
y[3:,2:]  ## lat element

array([[98]])

In [62]:
## Boolean Masking
c1 = np.arange(10).reshape(5,2)
c1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
res =c1%2==0
res

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False]], dtype=bool)

### Other functions --> eye,zeros,ones,max,min,copy,transpose,fliplr

In [66]:
np.eye(4)   ## Identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [68]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [69]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [70]:
np.max(c1)

9

In [71]:
np.min(c1)

0

In [73]:
c2 = np.copy(c1)
c2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
np.transpose(c2)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [77]:
np.fliplr(c2)  ##use to reverse the column

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

In [78]:
np.invert(c2)

array([[ -1,  -2],
       [ -3,  -4],
       [ -5,  -6],
       [ -7,  -8],
       [ -9, -10]], dtype=int32)

In [79]:
x= np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [80]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])