In [1]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
#Measures of central Tendency --> mean,median,mode
ht = [160,152,160,142,125,180]
sp.mean(ht)

153.16666666666666

In [3]:
sp.median(ht)

156.0

In [4]:
np.mean(ht)

153.16666666666666

In [5]:
np.median(ht)

156.0

In [6]:
stats.mode(ht)

ModeResult(mode=array([160]), count=array([2]))

### Data Variability

* Range --> diff bet highest and lowest value
* SD --> quantify the amount of variation/dispersion of data values
* Var --> square of SD is variance

* Outliers --> data point is very far/distinct from observation
* Z-Score
* Emperical Rule
* Percentile --> Group observation faill within 
--> minimum value ;- 0 percentile
--> Maximum value ;- 100 percentile



In [7]:
np.max(ht)

180

In [8]:
np.min(ht)

125

In [9]:
range1= np.max(ht) - np.min(ht)
range1

55

In [10]:
## SD --> sum(X-mean)
np.std(ht)

16.994280083473839

In [11]:
np.var(ht)

288.8055555555556

In [12]:
stats.zscore(ht)
## -ve values lies left hand side +ve values lies right hand side

array([ 0.40209608, -0.06865055,  0.40209608, -0.65708383, -1.65742041,
        1.57896264])

In [13]:
np.percentile(ht,0)

125.0

In [14]:
np.percentile(ht,25) # Q1

144.5

In [15]:
np.percentile(ht,50) #Q2

156.0

In [16]:
np.percentile(ht,75) #Q3

160.0

In [17]:
# IQR = Q3-Q1
# IQR = 75-25
np.percentile(ht,75) - np.percentile(ht,25)


15.5

In [18]:
## Outliers
Q1-1.5*IQR < val or Q3+1.5*IQR > val

NameError: name 'Q1' is not defined

* Q1 = 25(percentile)
* Q2 = 50(percentile)
* Q3 = 75(percentile)

In [ ]:
plt.hist(ht)
plt.show()

In [ ]:
import seaborn as sns
sns.distplot(ht)

* Central Limit Theorm
* t-Test
* ANOVA test



#### Histogram Normalization

* Normal Distribution
* Binomial
* Right Skewed
* Left Skewed

### Normality Testing

* Skewness --> is a measure of asymmetry of the probability distibution of real valued random variable
* Kurtosis --> is a measure of the tailedness 
* Kurtosis >3 is abnormal
* Kurtosis <3 is a normal distribution

In [ ]:
from scipy import stats

In [ ]:
## Skewness --> -1.96 to 1.96 (not a skewness)
## Kurtosis --> -3 to 3 (not a kurtosis)

In [ ]:
stats.skew(ht)

In [ ]:
stats.kurtosis(ht)

In [ ]:
np.mean(ht)

In [ ]:
stats.mode(ht)

In [ ]:
np.median(ht)

### Hypothesis Testing
* H0: Null hypothesis 
* Ha: Alteranate hypothesis

* H0: Marriage age of male in India is 30
* Ha: marriage age of male in India is not 30 
* 30 is the hypothesis mean


In [19]:
mar_age = [39,47,40,39,18,31,42,38,32,40]
mar_age

[39, 47, 40, 39, 18, 31, 42, 38, 32, 40]

In [20]:
sp.mean(mar_age)

36.600000000000001

In [21]:
print(stats.skew(mar_age))
stats.kurtosis(mar_age)

-1.2276505050194506


1.0900119691702308

In [22]:
# One Sample T Test
stats.ttest_1samp(mar_age,30)

Ttest_1sampResult(statistic=2.6170702328698763, pvalue=0.02794486941269694)

In [23]:
mar_age1 = [30,34,31,32,28,33,22,35,32,30]
mar_age1

[30, 34, 31, 32, 28, 33, 22, 35, 32, 30]

In [24]:
stats.ttest_1samp(mar_age1,30)

Ttest_1sampResult(statistic=0.60098199738374891, pvalue=0.56267987967198718)

In [25]:
sp.mean(mar_age1)

30.699999999999999

In [26]:
print(stats.skew(mar_age1))
stats.kurtosis(mar_age)

-1.2817011639535487


1.0900119691702308

In [27]:
mar_age_us = [36,35,38,29,40,31,29,32,38,37]
mar_age_us

[36, 35, 38, 29, 40, 31, 29, 32, 38, 37]

H0: Marriage age of male in India and us are same
Ha: Marriage age of male in India and us are not same

In [28]:
stats.ttest_ind(mar_age,mar_age_us)

Ttest_indResult(statistic=0.74510572606376435, pvalue=0.46582633162313136)

In [29]:
sp.mean(mar_age)

36.600000000000001

In [30]:
stats.ttest_ind(mar_age1,mar_age_us)

Ttest_indResult(statistic=-2.2162050053752567, pvalue=0.039800600935506449)

In [31]:
sp.mean(mar_age1)

30.699999999999999

In [33]:
sp.mean(mar_age_us)

34.5

### Two Sample t test

H0: Response time of lemon and coffee are same
Ha: Response time of lemon and coffee are not same

In [34]:
le = [36,12,46,10,15,20]

c= [33,10,38,12,13,19]

In [35]:
stats.ttest_rel(le,c)

Ttest_relResult(statistic=1.75, pvalue=0.14052235898854237)

#### Anova Test-more than 2 variables

H0: Response time of lemon, coffee and redbull are same
Ha: Response time of lemon, coffee and redbull are not same

In [37]:
le = [36,12,46,10,15,20]
c = [33,10,38,12,13,19]
rb = [31,9,39,13,10,15]

In [38]:
from scipy.stats import f_oneway

In [39]:
f_oneway(le,c,rb)

F_onewayResult(statistic=0.12208729898260585, pvalue=0.88594158165481351)

In [41]:
from scipy.stats import chi2_contingency

#definig the table
data = [[207,282,242],[234,242,232]]
stat, p, dof, expected = chi2_contingency(data)

# interpret p-value
alpha = 0.05
print("p value is ",p)
if p<= alpha:
    print('Dependent (reject HO)')
else:
    print('Independent (HO holds true)')

p value is  0.102744853209
Independent (HO holds true)


In [42]:
print(dof) # degree of freedom(r-1)*(c-1)


2


In [43]:
print(stat)

4.55101303456


In [44]:
print(expected)

[[ 224.02432245  266.1876303   240.78804726]
 [ 216.97567755  257.8123697   233.21195274]]
